FROM python:3.9-slim-buster
# Imagem base

# Define o diretório de trabalho
WORKDIR /

# Copia os arquivos do projeto
COPY . .

# Instala as dependências e dando permissões
RUN pip install --no-cache-dir -r requirements.txt 
RUN chmod +x start.sh

# Formatação utilizando comando sed para padronização unicode(linux/windows)
RUN sed -i 's/\r//' start.sh
RUN sed -i 's/\r//' cron.sh

# Expondo a porta
EXPOSE 8081