# Reference: https://github.com/roboll/helmfile
# https://www.arthurkoziel.com/managing-helm-charts-with-helmfile/

# Path to alternative helm binary (--helm-binary)
#helmBinary: /usr/local/bin/helm

helmDefaults:
  # wait for k8s resources via --wait. (default false)
  wait: false
  # if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout (default false, Implemented in Helm3.5)
  waitForJobs: false
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 1500
  # limit the maximum number of revisions saved per release. Use 0 for no limit. (default 10)
  historyMax: 20
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true
  # restores previous state in case of failed release (default false)
  atomic: false

templates:
  default: &default
    chart: ..\charts\devops-prova
    namespace: devops-prova
    missingFileHandler: Warn

releases:
  - name: database
    <<: *default
    values:
      - database_values.yaml
  - name: backend
    <<: *default
    values:
      - backend_values.yaml
  - name: frontend
    <<: *default
    values:
      - frontend_values.yaml
